In [1]:
import torch
import numpy as np
import torch.nn as nn
from torch.autograd import Variable

In [2]:
import matplotlib.pyplot as plt

%matplotlib inline
torch.manual_seed(3)

### Importing Dataset :

The dataset consists of records of individual test performances. Each record includes test scores. 

x_data contains all rows and all columns except the last one, representing the input features. y_data contains all rows and only the last column, representing the target variable. 

In [3]:
dataframe = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

x_data = dataframe[:, 0:-1]
y_data = dataframe[:, [-1]]

print('x_data :', x_data)
print('y_data :', y_data)

x_data : [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
y_data : [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


x_data and y_data, which are NumPy arrays are converted into PyTorch Variables

In [4]:
x = Variable(torch.from_numpy(x_data))
y = Variable(torch.from_numpy(y_data))
x, y

(tensor([[ 73.,  80.,  75.],
         [ 93.,  88.,  93.],
         [ 89.,  91.,  90.],
         [ 96.,  98., 100.],
         [ 73.,  66.,  70.],
         [ 53.,  46.,  55.],
         [ 69.,  74.,  77.],
         [ 47.,  56.,  60.],
         [ 87.,  79.,  90.],
         [ 79.,  70.,  88.],
         [ 69.,  70.,  73.],
         [ 70.,  65.,  74.],
         [ 93.,  95.,  91.],
         [ 79.,  80.,  73.],
         [ 70.,  73.,  78.],
         [ 93.,  89.,  96.],
         [ 78.,  75.,  68.],
         [ 81.,  90.,  93.],
         [ 88.,  92.,  86.],
         [ 78.,  83.,  77.],
         [ 82.,  86.,  90.],
         [ 86.,  82.,  89.],
         [ 78.,  83.,  85.],
         [ 76.,  83.,  71.],
         [ 96.,  93.,  95.]]),
 tensor([[152.],
         [185.],
         [180.],
         [196.],
         [142.],
         [101.],
         [149.],
         [115.],
         [175.],
         [164.],
         [141.],
         [141.],
         [184.],
         [152.],
         [148.],
         [192.],
 

In [5]:
mv_model = nn.Linear(3, 1, bias=True)

print(mv_model)

Linear(in_features=3, out_features=1, bias=True)


In [6]:
print('weigh : ', mv_model.weight)
print('bias  : ', mv_model.bias)

weigh :  Parameter containing:
tensor([[-0.5724, -0.4554, -0.2473]], requires_grad=True)
bias  :  Parameter containing:
tensor([-0.5462], requires_grad=True)


### Creating Cost Function :

Initializing mean squared error (MSE) cost function using nn.MSELoss() module for measuring the difference between predicted and target values.

In [7]:
cost_func = nn.MSELoss()
cost_func

MSELoss()

In [8]:
optimizer = torch.optim.SGD(mv_model.parameters(), lr=1e-5)

# Training Multivariant Linear Model :

Training multivariate linear regression model using a loop that runs for 2000 steps which calculates predictions, computes the cost, performs backpropagation to update model parameters, and monitors progress by printing cost and predictions every 50 steps.

In [9]:
for step in range(2000):
    optimizer.zero_grad()
    
    prediction = mv_model(x)
    cost = cost_func(prediction, y)
    cost.backward()
    
    optimizer.step()
    
    if step % 50 == 0:
        print(step, "Cost: ", cost.data.numpy(), "\nPrediction:\n", prediction.data.t().numpy())

0 Cost:  71245.445 
Prediction:
 [[ -97.31593  -116.85925  -115.19403  -124.862045  -89.70321   -65.43636
   -92.7881    -67.79273  -108.583786  -99.41075   -89.97716   -88.51963
  -119.55282  -100.25592   -93.15237  -118.056564  -96.16981  -110.901024
  -114.0879   -102.038994 -108.9098   -109.13042  -104.017296  -99.41041
  -121.34835 ]]
50 Cost:  7.937664 
Prediction:
 [[153.61766  184.76898  181.98889  198.80785  140.33221  104.186134
  149.50446  111.8474   173.33453  161.75027  143.45233  141.66547
  187.46323  154.94461  150.25993  188.03688  146.86583  179.87653
  178.6011   159.84747  175.21548  173.85023  166.86697  153.55559
  191.2427  ]]
100 Cost:  7.861643 
Prediction:
 [[153.59712 184.7723  181.97649 198.80943 140.32924 104.21049 149.52022
  111.87867 173.36256 161.81209 143.46037 141.69151 187.43544 154.90178
  150.28163 188.05205 146.81538 179.89851 178.56789 159.81747 175.23265
  173.86629 166.87666 153.49994 191.23463]]
150 Cost:  7.788775 
Prediction:
 [[153.57712  

1550 Cost:  6.6063695 
Prediction:
 [[153.18222 184.81964 181.71515 198.85092 140.23163 104.70489 149.8826
  112.59452 173.93161 163.10843 143.63731 142.23178 186.84097 153.97742
  150.76328 188.3605  145.70834 180.41325 177.86517 159.18869 175.6202
  174.19405 167.10686 152.32516 191.04431]]
1600 Cost:  6.5842767 
Prediction:
 [[153.17278 184.82004 181.70885 198.85219 140.22812 104.71622 149.89236
  112.61372 173.94466 163.13957 143.64186 142.24455 186.82631 153.95436
  150.77574 188.3676  145.68013 180.4274  177.8481  159.17361 175.63043
  174.20161 167.1133  152.29668 191.03905]]
1650 Cost:  6.5630574 
Prediction:
 [[153.16357 184.82037 181.70265 198.85344 140.22461 104.72725 149.90196
  112.63261 173.95737 163.16998 143.64629 142.257   186.81192 153.93173
  150.78796 188.37448 145.6524  180.44133 177.83136 159.15886 175.64049
  174.209   167.11963 152.26883 191.03384]]
1700 Cost:  6.542657 
Prediction:
 [[153.15463 184.82066 181.6966  198.85468 140.2211  104.73801 149.9114
  112.65

In [10]:
accuracy_list = []
for i,real_y in enumerate(y):
    accuracy = (mv_model((x[i])).data.numpy() - real_y.data.numpy())
    accuracy_list.append(np.absolute(accuracy))

for accuracy in accuracy_list:
    print(accuracy)

print("sum accuracy : ",sum(accuracy_list))
print("avg accuracy : ",sum(accuracy_list)/len(y))

[1.1056824]
[0.17875671]
[1.6630096]
[2.8618317]
[1.7998505]
[3.7968597]
[0.9650421]
[2.2432556]
[0.96255493]
[0.63565063]
[2.6750946]
[1.3362274]
[2.7194061]
[1.7856903]
[2.8675537]
[3.5819702]
[1.5274506]
[2.4665985]
[0.7240906]
[0.0645752]
[1.2937164]
[0.7443695]
[7.8383026]
[3.0903015]
[1.0005951]
sum accuracy :  [49.928436]
avg accuracy :  [1.9971374]
