## Pytorch :

PyTorch is an open-source machine learning framework that excels in building and training deep learning models. Its dynamic computation graph, automatic differentiation, and GPU support make it popular among researchers and developers. It provides tools for creating tensors, defining neural networks, loading data, and optimizing models.

In [1]:
import torch

### Tensors :

 Tensors are multi-dimensional arrays similar to NumPy arrays but with additional capabilities optimized for deep learning. Tensors in PyTorch are the fundamental building blocks for creating and manipulating data in the framework.

### Tensor Basic :

'torch.tensor' is used for creating and manipulating multi-dimensional arrays (tensors) used in deep learning.

In [3]:
x = torch.Tensor(2, 3)
print(x)

tensor([[9.2755e-39, 9.3673e-39, 9.9184e-39],
        [2.9389e-39, 1.0286e-38, 9.0919e-39]])


In [4]:
print("Tensor size :", x.size())
print("Tensor type :", x.type())

Tensor size : torch.Size([2, 3])
Tensor type : torch.FloatTensor


### Tensor With Characterstics :

torch.zeros creates a tensor filled with zeros of a specified size.

In [5]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
print("Tensor size:", x.size())
print("Temsor type:", x.type())

Tensor size: torch.Size([2, 3])
Temsor type: torch.FloatTensor


In [9]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [10]:
print("Torch size:", x.size())
print("Torch typr:", x.type())

Torch size: torch.Size([2, 3])
Torch typr: torch.IntTensor


torch.ones generates a tensor filled with ones of a specified size.

In [11]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
print("Torch size:", x.size())
print("Torch type:", x.type())

Torch size: torch.Size([2, 3])
Torch type: torch.FloatTensor



torch.rand produces a tensor with random values between 0 and 1 of a specified size.

In [13]:
x = torch.rand(2, 3)
print(x)

tensor([[0.9499, 0.3418, 0.2776],
        [0.2030, 0.5897, 0.3446]])


In [14]:
print("Tensor type:", x.type())
print("Tensor size", x.size())

Tensor type: torch.FloatTensor
Tensor size torch.Size([2, 3])


torch.randn generates a tensor with random values drawn from a standard normal distribution (mean 0, standard deviation 1) of a specified size.

In [15]:
x = torch.randn(2, 3)
print(x)
print('Tensor size', x.size())
print('Tensor type:', x.type())

tensor([[-0.2270, -1.1953, -0.3041],
        [ 0.6390,  1.2507, -0.3373]])
Tensor size torch.Size([2, 3])
Tensor type: torch.FloatTensor


torch.eye creates an identity matrix as a tensor with ones on the diagonal and zeros elsewhere, of a specified size.

In [17]:
x = torch.eye(2, 3)
print(x)
print("Tensor size:", x.size())
print("Tensor type:", x.type())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor size: torch.Size([2, 3])
Tensor type: torch.FloatTensor



torch.arange generates a tensor with a sequence of values from start to end with a specified step size.

In [19]:
x = torch.arange(2, 3)
print(x)
print("Tensor size:", x.size())
print("Tensor type:", x.type())

tensor([2])
Tensor size: torch.Size([1])
Tensor type: torch.LongTensor


torch.tensor is a constructor that creates a new PyTorch tensor from a given data source, like a list or an array-like structure.

In [20]:
x = torch.Tensor(2, 3)
print(x)
print("Tensor size:", x.size())
print("Tensor type:", x.type())

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3446]])
Tensor size: torch.Size([2, 3])
Tensor type: torch.FloatTensor


Create a tensor of data type float

In [23]:
x = torch.FloatTensor(2, 3)
print(x)
print("Tensor size:", x.size())
print("Tensor type:", x.type())

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [3.2175e+21, 2.6081e+20, 1.3029e-11]])
Tensor size: torch.Size([2, 3])
Tensor type: torch.FloatTensor


Creates a tensor of data type int

In [24]:
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[          0,           0,           0],
        [          0,           0, -1095978729]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


### Tensor And NUmpy :

NumPy is a Python library for numerical computations, providing support for multi-dimensional arrays (tensors), mathematical functions, and operations, making it essential for scientific computing and data analysis.

In [25]:
import numpy as np

In [29]:
x = np.array([[1, 2, 3], [1, 2, 3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


torch.from_numpy creates a PyTorch tensor from a NumPy array 

In [30]:
x = torch.from_numpy(x)
print(x)
print("Tensor size :", x.size())
print("Tensor type :", x.type())

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)
Tensor size : torch.Size([2, 3])
Tensor type : torch.IntTensor


### Tensor Slicing :

Tensor slicing involves extracting a portion of a tensor using indexing. It's a way to access specific elements, rows, columns, or sub-tensors.

In [35]:
x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)
print('Tensor size:', x.size())
print('Tensor type:', x.type())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
Tensor size: torch.Size([3, 4])
Tensor type: torch.FloatTensor


Slice all dimensions of a tensor x in one line, effectively selecting all elements.

In [36]:
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

Selects all rows and all columns starting from the second column of the tensor x in one line.

In [38]:
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

Selects all rows and all columns starting from the third column of the tensor x.

In [39]:
x[:, 2:]

tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])

selects a sub-tensor from the tensor x, excluding the first row and including columns 1 and 2.

In [41]:
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

torch.split is used to split a tensor into multiple chunks along a specified dimension.

In [49]:
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [42]:
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [43]:
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [44]:
torch.masked_select(x_cols[0], torch.BoolTensor([[0,1],[1,0],[0,1]]).bool())

tensor([ 2.,  5., 10.])

### Tensor Merging :

Tensor merging refers to combining multiple tensors into a single tensor, typically along a specified dimension or using a concatenation operation.

torch.cat concatenates a sequence of tensors along a specified dimension

In [50]:
torch.cat(x_rows, dim = 0)
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [51]:
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

torch.stack creates a new tensor by stacking a sequence of tensors along a new dimension in one line.

In [52]:
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


### Tensor Reshaping :

In [53]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


torch.view views the tensor in specified rows an columns

In [54]:
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [55]:
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [56]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [57]:
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [58]:
x.view(2, 1, -1).squeeze().unsqueeze(dim=1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

### Tensor Calculation :

Tensor calculations involve performing various mathematical operations, such as addition, subtraction, multiplication, division, and more, on tensors. These operations can be element-wise or involve operations between entire tensors, often used in mathematical modeling, machine learning, and scientific computing.

In [59]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [63]:
z = torch.add(x, y)
print(x)
print('z :', z )
print('x + y :', x+y)

tensor([[2., 3., 4.],
        [6., 7., 8.]])
z : tensor([[ 3.,  4.,  5.],
        [ 8.,  9., 10.]])
x + y : tensor([[ 3.,  4.,  5.],
        [ 8.,  9., 10.]])


In [64]:
print(x - 2)

tensor([[0., 1., 2.],
        [4., 5., 6.]])


In [65]:
print(x*2)

tensor([[ 4.,  6.,  8.],
        [12., 14., 16.]])


In [66]:
print(2*x)

tensor([[ 4.,  6.,  8.],
        [12., 14., 16.]])


In [67]:
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 2.,  3.,  4.],
        [12., 14., 16.]])
x*y : tensor([[ 2.,  3.,  4.],
        [12., 14., 16.]])


In [68]:
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 4.,  9., 16.],
        [36., 49., 64.]])
x**2 : tensor([[ 4.,  9., 16.],
        [36., 49., 64.]])


In [69]:
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.6931, 1.0986, 1.3863],
        [1.7918, 1.9459, 2.0794]])
x.log() : tensor([[0.6931, 1.0986, 1.3863],
        [1.7918, 1.9459, 2.0794]])


In [70]:
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.4142, 1.7321, 2.0000],
        [2.4495, 2.6458, 2.8284]])
x.sqrt() : tensor([[1.4142, 1.7321, 2.0000],
        [2.4495, 2.6458, 2.8284]])


In [71]:
z = x % 2
print(z)

tensor([[0., 1., 0.],
        [0., 1., 0.]])


In [72]:
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x.abs() : tensor([[2., 3., 4.],
        [6., 7., 8.]])


### Tensor Casting : 

Tensor casting refers to changing the data type of a tensor from one numerical type to another, such as converting from integers to floating-point numbers or vice versa. This can be important for ensuring compatibility in mathematical operations and precision requirements.

In [73]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [74]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [75]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [76]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [78]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Tensor Statics :


Tensor statistics involve calculating various numerical properties of tensors, such as mean, standard deviation, minimum, and maximum values, which are essential for understanding the data distribution and performing data analysis.

In [79]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [82]:
print('Sum :', x.sum())
print('Min :', x.min())
print('Max :', x.max())
print('Var :', x.var())

Sum : tensor(3.)
Min : tensor(-5.)
Max : tensor(6.)
Var : tensor(17.9000)


In [83]:
x.sum()

tensor(3.)

In [84]:
x.sum().size()

torch.Size([])

In [85]:
print('Sum Item:', x.sum().item())
print('Min Item:', x.min().item())
print('Max Item:', x.max().item())
print('Var Item :', x.var().item())

Sum Item: 3.0
Min Item: -5.0
Max Item: 6.0
Var Item : 17.899999618530273


In [86]:
value, index = x.max(dim=0)
value, index

(tensor([4., 2., 6.]), tensor([1, 0, 1]))

In [87]:
value, index = x.max(dim=1)
value, index

(tensor([2., 6.]), tensor([1, 2]))

In [88]:
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

### Like Function :

In [89]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])



torch.zeros_like creates a tensor of zeros with the same shape as the input tensor 

In [90]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])



torch.ones_like creates a tensor of ones with the same shape as the input tensor 

In [91]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [92]:
y = torch.rand_like(x)
print(y)

tensor([[0.5377, 0.6848, 0.0017],
        [0.7292, 0.1438, 0.7800]])


### Tensor Calculation As Matrix  :


Performing tensor calculations as matrices involves using mathematical operations on tensors, often in a matrix-like manner, to solve linear equations, transform data, or perform operations like matrix multiplication, inversion, and decomposition.

In [96]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])



torch.mm computes the matrix multiplication between two tensors in one line.

In [97]:
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [98]:
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

`torch.dot` calculates the dot product between two 1-dimensional tensors in one line.

In [99]:
torch.dot(z, z)

tensor(5.)

In [100]:
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [101]:
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [102]:
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

torch.bmm(x1,x2).size()

torch.Size([3, 3, 3])

In [103]:
x1

tensor([[[1.0194e-38, 9.9184e-39],
         [2.9389e-39, 1.0194e-38],
         [2.9389e-39, 9.2755e-39]],

        [[9.0918e-39, 1.0010e-38],
         [9.9184e-39, 1.0653e-38],
         [9.1837e-39, 9.6428e-39]],

        [[1.0010e-38, 9.1837e-39],
         [8.9082e-39, 9.2755e-39],
         [1.1112e-38, 0.0000e+00]]])

In [104]:
x2

tensor([[[9.0919e-39, 9.2755e-39, 2.9389e-39],
         [1.0286e-38, 1.0469e-38, 1.0653e-38]],

        [[1.0194e-38, 2.9389e-39, 1.0194e-38],
         [9.9184e-39, 2.9389e-39, 1.0194e-38]],

        [[2.9389e-39, 9.2755e-39, 9.0918e-39],
         [1.0010e-38, 9.9184e-39, 1.0653e-38]]])


x.transpose returns the transpose of a tensor x, swapping its dimensions in one line.

In [105]:
x1.transpose(0,2)

tensor([[[1.0194e-38, 9.0918e-39, 1.0010e-38],
         [2.9389e-39, 9.9184e-39, 8.9082e-39],
         [2.9389e-39, 9.1837e-39, 1.1112e-38]],

        [[9.9184e-39, 1.0010e-38, 9.1837e-39],
         [1.0194e-38, 1.0653e-38, 9.2755e-39],
         [9.2755e-39, 9.6428e-39, 0.0000e+00]]])

torch.linalg.eig computes the eigenvalues and eigenvectors of a square matrix in one line.

In [108]:
eigenvalue, eigenvector = torch.linalg.eig(x)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

eigenvalue : tensor([1.1921e-07+0.j, 3.0000e+00+0.j])
eigenvector : tensor([[-0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j, -0.8944+0.j]])


torch.qr computes the QR decomposition of a matrix, factorizing it into an orthogonal and an upper triangular matrix in one line.

In [109]:
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
R : tensor([[-2.2361e+00, -2.2361e+00],
        [ 0.0000e+00,  1.1921e-07]])


C:\Users\DELL\AppData\Local\Temp\ipykernel_2632\4160111081.py:1: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2431.)
  Q,R = torch.qr(x)


torch.svd performs Singular Value Decomposition on a tensor, factorizing it into three tensors in one line.

In [110]:
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
V : tensor([3.1623e+00, 5.2283e-08])
D : tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])
